apiVersion: v1
kind: ServiceAccount
metadata:
  name: maas-controller
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
