{{- if .Values.keycloak.deploy }}
{{- $kcNs := include "maas.keycloak.namespace" . }}
{{- $existingAdmin := lookup "v1" "Secret" $kcNs "keycloak-admin" }}
{{- $adminPassword := "" }}
{{- if and $existingAdmin (not .Values.keycloak.adminPassword) }}
  {{- $adminPassword = index $existingAdmin.data "password" | b64dec }}
{{- else }}
  {{- $adminPassword = .Values.keycloak.adminPassword | default (randAlphaNum 24) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: {{ $kcNs }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  username: {{ .Values.keycloak.adminUser | default "admin" }}
  password: {{ $adminPassword }}
---
{{- $existingClient := lookup "v1" "Secret" $kcNs "keycloak-client-secret" }}
{{- $clientSecret := "" }}
{{- if and $existingClient (not .Values.keycloak.clientSecret) }}
  {{- $clientSecret = index $existingClient.data "client-secret" | b64dec }}
{{- else }}
  {{- $clientSecret = .Values.keycloak.clientSecret | default (randAlphaNum 32) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
  namespace: {{ $kcNs }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  client-secret: {{ $clientSecret }}
{{- end }}
