{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        {{- include "maas.labels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      {{- if .Values.pullSecret.dockerConfigJson }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret.name }}
      {{- end }}
      containers:
      - name: postgresql
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRESQL_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRESQL_PASSWORD
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRESQL_DATABASE
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/pgsql/data
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U maas -d {{ .Values.postgresql.database }}
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U maas -d {{ .Values.postgresql.database }}
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
{{- end }}
