{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRESQL_USER: maas
  POSTGRESQL_PASSWORD: maas-dev-password
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  DB_CONNECTION_URL: "postgresql://maas:maas-dev-password@postgres.{{ include "maas.namespace" . }}.svc.cluster.local:5432/{{ .Values.postgresql.database }}?sslmode=disable"
{{- end }}
