apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: maas-authorino-allow
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: maas-api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kuadrant-system
      podSelector:
        matchLabels:
          authorino-resource: authorino
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kuadrant-operators
      podSelector:
        matchLabels:
          authorino-resource: authorino
    ports:
    - port: 8080
      protocol: TCP
