{{- if and .Values.pullSecret.dockerConfigJson .Values.pullSecret.create }}
{{- if not (lookup "v1" "Secret" (include "maas.namespace" .) .Values.pullSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerConfigJson | b64enc | quote }}
{{- end }}
{{- end }}
