apiVersion: v1
kind: ConfigMap
metadata:
  name: tier-to-group-mapping
  namespace: {{ include "maas.namespace" . }}
  labels:
    {{- include "maas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  tiers: |
    {{- .Values.tierMapping.tiers | nindent 4 }}
